/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_Harry_WRAP_H_
#define SWIG_Harry_WRAP_H_

class SwigDirector_CallbackStub : public CallbackStub, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_CallbackStub(JNIEnv *jenv);
    virtual ~SwigDirector_CallbackStub();
    virtual void on_void_method();
    virtual char *on_string_method(char *msg);
    virtual signed char *on_byte_array_method(signed char arr[]);
public:
    bool swig_overrides(int n) {
      return (n < 3 ? swig_override[n] : false);
    }
protected:
    bool swig_override[3];
};


#endif
