/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGJAVA
#define SWIG_DIRECTORS


#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  jenv->ExceptionClear();
  excep = jenv->FindClass(except_ptr->java_exception);
  if (excep)
    jenv->ThrowNew(excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else

/* -----------------------------------------------------------------------------
 * director.swg
 *
 * This file contains support for director classes that proxy
 * method calls from C++ to Java extensions.
 * ----------------------------------------------------------------------------- */

#ifdef __cplusplus

#if defined(DEBUG_DIRECTOR_OWNED)
#include <iostream>
#endif

namespace Swig {
  /* Java object wrapper */
  class JObjectWrapper {
  public:
    JObjectWrapper() : jthis_(NULL), weak_global_(true) {
    }

    ~JObjectWrapper() {
      jthis_ = NULL;
      weak_global_ = true;
    }

    bool set(JNIEnv *jenv, jobject jobj, bool mem_own, bool weak_global) {
      if (!jthis_) {
        weak_global_ = weak_global;
        if (jobj)
          jthis_ = ((weak_global_ || !mem_own) ? jenv->NewWeakGlobalRef(jobj) : jenv->NewGlobalRef(jobj));
#if defined(DEBUG_DIRECTOR_OWNED)
        std::cout << "JObjectWrapper::set(" << jobj << ", " << (weak_global ? "weak_global" : "global_ref") << ") -> " << jthis_ << std::endl;
#endif
        return true;
      } else {
#if defined(DEBUG_DIRECTOR_OWNED)
        std::cout << "JObjectWrapper::set(" << jobj << ", " << (weak_global ? "weak_global" : "global_ref") << ") -> already set" << std::endl;
#endif
        return false;
      }
    }

    jobject get(JNIEnv *jenv) const {
#if defined(DEBUG_DIRECTOR_OWNED)
      std::cout << "JObjectWrapper::get(";
      if (jthis_)
        std::cout << jthis_;
      else
        std::cout << "null";
      std::cout << ") -> return new local ref" << std::endl;
#endif
      return (jthis_ ? jenv->NewLocalRef(jthis_) : jthis_);
    }

    void release(JNIEnv *jenv) {
#if defined(DEBUG_DIRECTOR_OWNED)
      std::cout << "JObjectWrapper::release(" << jthis_ << "): " << (weak_global_ ? "weak global ref" : "global ref") << std::endl;
#endif
      if (jthis_) {
        if (weak_global_) {
          if (jenv->IsSameObject(jthis_, NULL) == JNI_FALSE)
            jenv->DeleteWeakGlobalRef((jweak)jthis_);
        } else
          jenv->DeleteGlobalRef(jthis_);
      }

      jthis_ = NULL;
      weak_global_ = true;
    }

    jobject peek() {
      return jthis_;
    }

    /* Java proxy releases ownership of C++ object, C++ object is now
       responsible for destruction (creates NewGlobalRef to pin Java
       proxy) */
    void java_change_ownership(JNIEnv *jenv, jobject jself, bool take_or_release) {
      if (take_or_release) {  /* Java takes ownership of C++ object's lifetime. */
        if (!weak_global_) {
          jenv->DeleteGlobalRef(jthis_);
          jthis_ = jenv->NewWeakGlobalRef(jself);
          weak_global_ = true;
        }
      } else { /* Java releases ownership of C++ object's lifetime */
        if (weak_global_) {
          jenv->DeleteWeakGlobalRef((jweak)jthis_);
          jthis_ = jenv->NewGlobalRef(jself);
          weak_global_ = false;
        }
      }
    }

  private:
    /* pointer to Java object */
    jobject jthis_;
    /* Local or global reference flag */
    bool weak_global_;
  };

  /* director base class */
  class Director {
    /* pointer to Java virtual machine */
    JavaVM *swig_jvm_;

  protected:
#if defined (_MSC_VER) && (_MSC_VER<1300)
    class JNIEnvWrapper;
    friend class JNIEnvWrapper;
#endif
    /* Utility class for managing the JNI environment */
    class JNIEnvWrapper {
      const Director *director_;
      JNIEnv *jenv_;
      int env_status;
    public:
      JNIEnvWrapper(const Director *director) : director_(director), jenv_(0), env_status(0) {
#if defined(__ANDROID__)
        JNIEnv **jenv = &jenv_;
#else
        void **jenv = (void **)&jenv_;
#endif
        env_status = director_->swig_jvm_->GetEnv((void **)&jenv_, JNI_VERSION_1_2);
#if defined(SWIG_JAVA_ATTACH_CURRENT_THREAD_AS_DAEMON)
        // Attach a daemon thread to the JVM. Useful when the JVM should not wait for 
        // the thread to exit upon shutdown. Only for jdk-1.4 and later.
        director_->swig_jvm_->AttachCurrentThreadAsDaemon(jenv, NULL);
#else
        director_->swig_jvm_->AttachCurrentThread(jenv, NULL);
#endif
      }
      ~JNIEnvWrapper() {
#if !defined(SWIG_JAVA_NO_DETACH_CURRENT_THREAD)
        // Some JVMs, eg jdk-1.4.2 and lower on Solaris have a bug and crash with the DetachCurrentThread call.
        // However, without this call, the JVM hangs on exit when the thread was not created by the JVM and creates a memory leak.
        if (env_status == JNI_EDETACHED)
          director_->swig_jvm_->DetachCurrentThread();
#endif
      }
      JNIEnv *getJNIEnv() const {
        return jenv_;
      }
    };

    /* Java object wrapper */
    JObjectWrapper swig_self_;

    /* Disconnect director from Java object */
    void swig_disconnect_director_self(const char *disconn_method) {
      JNIEnvWrapper jnienv(this) ;
      JNIEnv *jenv = jnienv.getJNIEnv() ;
      jobject jobj = swig_self_.peek();
#if defined(DEBUG_DIRECTOR_OWNED)
      std::cout << "Swig::Director::disconnect_director_self(" << jobj << ")" << std::endl;
#endif
      if (jobj && jenv->IsSameObject(jobj, NULL) == JNI_FALSE) {
        jmethodID disconn_meth = jenv->GetMethodID(jenv->GetObjectClass(jobj), disconn_method, "()V");
        if (disconn_meth) {
#if defined(DEBUG_DIRECTOR_OWNED)
          std::cout << "Swig::Director::disconnect_director_self upcall to " << disconn_method << std::endl;
#endif
          jenv->CallVoidMethod(jobj, disconn_meth);
        }
      }
    }

  public:
    Director(JNIEnv *jenv) : swig_jvm_((JavaVM *) NULL), swig_self_() {
      /* Acquire the Java VM pointer */
      jenv->GetJavaVM(&swig_jvm_);
    }

    virtual ~Director() {
      JNIEnvWrapper jnienv(this) ;
      JNIEnv *jenv = jnienv.getJNIEnv() ;
      swig_self_.release(jenv);
    }

    bool swig_set_self(JNIEnv *jenv, jobject jself, bool mem_own, bool weak_global) {
      return swig_self_.set(jenv, jself, mem_own, weak_global);
    }

    jobject swig_get_self(JNIEnv *jenv) const {
      return swig_self_.get(jenv);
    }

    // Change C++ object's ownership, relative to Java
    void swig_java_change_ownership(JNIEnv *jenv, jobject jself, bool take_or_release) {
      swig_self_.java_change_ownership(jenv, jself, take_or_release);
    }
  };
}

#endif /* __cplusplus */


namespace Swig {
  namespace {
    jclass jclass_HarryJNI = NULL;
    jmethodID director_methids[3];
  }
}

#include "../harry.h"


#include <string>



/* ---------------------------------------------------
 * C++ director class methods
 * --------------------------------------------------- */

#include "harry_wrap.h"

SwigDirector_CallbackStub::SwigDirector_CallbackStub(JNIEnv *jenv) : CallbackStub(), Swig::Director(jenv) {
}

SwigDirector_CallbackStub::~SwigDirector_CallbackStub() {
  swig_disconnect_director_self("swigDirectorDisconnect");
}


void SwigDirector_CallbackStub::on_void_method() {
  JNIEnvWrapper swigjnienv(this) ;
  JNIEnv * jenv = swigjnienv.getJNIEnv() ;
  jobject swigjobj = (jobject) NULL ;
  
  if (!swig_override[0]) {
    CallbackStub::on_void_method();
    return;
  }
  swigjobj = swig_get_self(jenv);
  if (swigjobj && jenv->IsSameObject(swigjobj, NULL) == JNI_FALSE) {
    jenv->CallStaticVoidMethod(Swig::jclass_HarryJNI, Swig::director_methids[0], swigjobj);
    if (jenv->ExceptionCheck() == JNI_TRUE) return ;
  } else {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null upcall object");
  }
  if (swigjobj) jenv->DeleteLocalRef(swigjobj);
}

char *SwigDirector_CallbackStub::on_string_method(char *msg) {
  char *c_result = 0 ;
  jstring jresult = 0 ;
  JNIEnvWrapper swigjnienv(this) ;
  JNIEnv * jenv = swigjnienv.getJNIEnv() ;
  jobject swigjobj = (jobject) NULL ;
  jstring jmsg = 0 ;
  
  if (!swig_override[1]) {
    return CallbackStub::on_string_method(msg);
  }
  swigjobj = swig_get_self(jenv);
  if (swigjobj && jenv->IsSameObject(swigjobj, NULL) == JNI_FALSE) {
    jmsg = 0;
    if (msg) {
      jmsg = jenv->NewStringUTF((const char *)msg);
      if (!jmsg) return c_result;
    }
    jresult = (jstring) jenv->CallStaticObjectMethod(Swig::jclass_HarryJNI, Swig::director_methids[1], swigjobj, jmsg);
    if (jenv->ExceptionCheck() == JNI_TRUE) return c_result;
    c_result = 0;
    if (jresult) {
      c_result = (char *)jenv->GetStringUTFChars(jresult, 0);
      if (!c_result) return c_result;
    }
  } else {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null upcall object");
  }
  if (swigjobj) jenv->DeleteLocalRef(swigjobj);
  return c_result;
}

signed char *SwigDirector_CallbackStub::on_byte_array_method(signed char arr[]) {
  signed char *c_result = 0 ;
  jlong jresult = 0 ;
  JNIEnvWrapper swigjnienv(this) ;
  JNIEnv * jenv = swigjnienv.getJNIEnv() ;
  jobject swigjobj = (jobject) NULL ;
  jlong jarr  ;
  
  if (!swig_override[2]) {
    return CallbackStub::on_byte_array_method(arr);
  }
  swigjobj = swig_get_self(jenv);
  if (swigjobj && jenv->IsSameObject(swigjobj, NULL) == JNI_FALSE) {
    *((signed char **)&jarr) = (signed char *) arr; 
    jresult = (jlong) jenv->CallStaticLongMethod(Swig::jclass_HarryJNI, Swig::director_methids[2], swigjobj, jarr);
    if (jenv->ExceptionCheck() == JNI_TRUE) return c_result;
    c_result = *(signed char **)&jresult; 
  } else {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "null upcall object");
  }
  if (swigjobj) jenv->DeleteLocalRef(swigjobj);
  return c_result;
}

void SwigDirector_CallbackStub::swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global) {
  static struct {
    const char *mname;
    const char *mdesc;
    jmethodID base_methid;
  } methods[] = {
    {
      "on_void_method", "()V", NULL 
    },
    {
      "on_string_method", "(Ljava/lang/String;)Ljava/lang/String;", NULL 
    },
    {
      "on_byte_array_method", "(Lcom/eric/swig/SWIGTYPE_p_signed_char;)Lcom/eric/swig/SWIGTYPE_p_signed_char;", NULL 
    }
  };
  
  static jclass baseclass = 0 ;
  
  if (swig_set_self(jenv, jself, swig_mem_own, weak_global)) {
    if (!baseclass) {
      baseclass = jenv->FindClass("com/eric/swig/CallbackStub");
      if (!baseclass) return;
      baseclass = (jclass) jenv->NewGlobalRef(baseclass);
    }
    bool derived = (jenv->IsSameObject(baseclass, jcls) ? false : true);
    for (int i = 0; i < 3; ++i) {
      if (!methods[i].base_methid) {
        methods[i].base_methid = jenv->GetMethodID(baseclass, methods[i].mname, methods[i].mdesc);
        if (!methods[i].base_methid) return;
      }
      swig_override[i] = false;
      if (derived) {
        jmethodID methid = jenv->GetMethodID(jcls, methods[i].mname, methods[i].mdesc);
        swig_override[i] = (methid != methods[i].base_methid);
        jenv->ExceptionClear();
      }
    }
  }
}



#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void JNICALL Java_com_eric_swig_HarryJNI_delete_1CallbackStub(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  CallbackStub *arg1 = (CallbackStub *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CallbackStub **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_com_eric_swig_HarryJNI_CallbackStub_1on_1void_1method(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  CallbackStub *arg1 = (CallbackStub *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CallbackStub **)&jarg1; 
  (arg1)->on_void_method();
}


SWIGEXPORT void JNICALL Java_com_eric_swig_HarryJNI_CallbackStub_1on_1void_1methodSwigExplicitCallbackStub(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  CallbackStub *arg1 = (CallbackStub *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CallbackStub **)&jarg1; 
  (arg1)->CallbackStub::on_void_method();
}


SWIGEXPORT jstring JNICALL Java_com_eric_swig_HarryJNI_CallbackStub_1on_1string_1method(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jstring jresult = 0 ;
  CallbackStub *arg1 = (CallbackStub *) 0 ;
  char *arg2 = (char *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CallbackStub **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)jenv->GetStringUTFChars(jarg2, 0);
    if (!arg2) return 0;
  }
  result = (char *)(arg1)->on_string_method(arg2);
  if (result) jresult = jenv->NewStringUTF((const char *)result);
  if (arg2) jenv->ReleaseStringUTFChars(jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_com_eric_swig_HarryJNI_CallbackStub_1on_1string_1methodSwigExplicitCallbackStub(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jstring jresult = 0 ;
  CallbackStub *arg1 = (CallbackStub *) 0 ;
  char *arg2 = (char *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CallbackStub **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)jenv->GetStringUTFChars(jarg2, 0);
    if (!arg2) return 0;
  }
  result = (char *)(arg1)->CallbackStub::on_string_method(arg2);
  if (result) jresult = jenv->NewStringUTF((const char *)result);
  if (arg2) jenv->ReleaseStringUTFChars(jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_eric_swig_HarryJNI_CallbackStub_1on_1byte_1array_1method(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CallbackStub *arg1 = (CallbackStub *) 0 ;
  signed char *arg2 ;
  signed char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CallbackStub **)&jarg1; 
  arg2 = *(signed char **)&jarg2; 
  result = (signed char *)(arg1)->on_byte_array_method(arg2);
  *(signed char **)&jresult = result; 
  
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_eric_swig_HarryJNI_CallbackStub_1on_1byte_1array_1methodSwigExplicitCallbackStub(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  CallbackStub *arg1 = (CallbackStub *) 0 ;
  signed char *arg2 ;
  signed char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CallbackStub **)&jarg1; 
  arg2 = *(signed char **)&jarg2; 
  result = (signed char *)(arg1)->CallbackStub::on_byte_array_method(arg2);
  *(signed char **)&jresult = result; 
  
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_eric_swig_HarryJNI_new_1CallbackStub(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  CallbackStub *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (CallbackStub *)new SwigDirector_CallbackStub(jenv);
  *(CallbackStub **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_eric_swig_HarryJNI_CallbackStub_1director_1connect(JNIEnv *jenv, jclass jcls, jobject jself, jlong objarg, jboolean jswig_mem_own, jboolean jweak_global) {
  CallbackStub *obj = *((CallbackStub **)&objarg);
  (void)jcls;
  SwigDirector_CallbackStub *director = dynamic_cast<SwigDirector_CallbackStub *>(obj);
  if (director) {
    director->swig_connect_director(jenv, jself, jenv->GetObjectClass(jself), (jswig_mem_own == JNI_TRUE), (jweak_global == JNI_TRUE));
  }
}


SWIGEXPORT void JNICALL Java_com_eric_swig_HarryJNI_CallbackStub_1change_1ownership(JNIEnv *jenv, jclass jcls, jobject jself, jlong objarg, jboolean jtake_or_release) {
  CallbackStub *obj = *((CallbackStub **)&objarg);
  SwigDirector_CallbackStub *director = dynamic_cast<SwigDirector_CallbackStub *>(obj);
  (void)jcls;
  if (director) {
    director->swig_java_change_ownership(jenv, jself, jtake_or_release ? true : false);
  }
}


SWIGEXPORT void JNICALL Java_com_eric_swig_HarryJNI_init(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  CallbackStub *arg1 = (CallbackStub *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(CallbackStub **)&jarg1; 
  init(arg1);
}


SWIGEXPORT void JNICALL Java_com_eric_swig_HarryJNI_void_1method(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  void_method();
}


SWIGEXPORT jstring JNICALL Java_com_eric_swig_HarryJNI_string_1method(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jstring jresult = 0 ;
  char *arg1 = (char *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)jenv->GetStringUTFChars(jarg1, 0);
    if (!arg1) return 0;
  }
  result = (char *)string_method(arg1);
  if (result) jresult = jenv->NewStringUTF((const char *)result);
  if (arg1) jenv->ReleaseStringUTFChars(jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_eric_swig_HarryJNI_byte_1array_1method(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  signed char *arg1 ;
  signed char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(signed char **)&jarg1; 
  result = (signed char *)byte_array_method(arg1);
  *(signed char **)&jresult = result; 
  
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_eric_swig_HarryJNI_void_1ptr_1method(JNIEnv *jenv, jclass jcls, void * jarg1) {
  jlong jresult = 0 ;
  void *arg1 = (void *) 0 ;
  void *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  
  arg1 = jarg1;
  
  result = (void *)void_ptr_method(arg1);
  *(void **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_eric_swig_HarryJNI_byte_1array_1input_1method(JNIEnv *jenv, jclass jcls, jbyteArray jarg1) {
  char *arg1 = (char *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  {
    arg1 = (char *) jenv->GetByteArrayElements(jarg1, 0);
    arg2 = (size_t) jenv->GetArrayLength(jarg1);
  }
  byte_array_input_method(arg1,arg2);
  {
    jenv->ReleaseByteArrayElements(jarg1, (jbyte *)arg1, 0);
  }
  
}


SWIGEXPORT jint JNICALL Java_com_eric_swig_HarryJNI_NET_1UDP_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  NetType result;
  
  (void)jenv;
  (void)jcls;
  result = (NetType)NET_UDP;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_eric_swig_HarryJNI_NET_1TCP_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  NetType result;
  
  (void)jenv;
  (void)jcls;
  result = (NetType)NET_TCP;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_eric_swig_HarryJNI_DefStruct_1value_1int_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  DefStruct *arg1 = (DefStruct *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DefStruct **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->value_int = arg2;
}


SWIGEXPORT jint JNICALL Java_com_eric_swig_HarryJNI_DefStruct_1value_1int_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  DefStruct *arg1 = (DefStruct *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DefStruct **)&jarg1; 
  result = (int) ((arg1)->value_int);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_eric_swig_HarryJNI_DefStruct_1net_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  DefStruct *arg1 = (DefStruct *) 0 ;
  NetType arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DefStruct **)&jarg1; 
  arg2 = (NetType)jarg2; 
  if (arg1) (arg1)->net = arg2;
}


SWIGEXPORT jint JNICALL Java_com_eric_swig_HarryJNI_DefStruct_1net_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  DefStruct *arg1 = (DefStruct *) 0 ;
  NetType result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DefStruct **)&jarg1; 
  result = (NetType) ((arg1)->net);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_eric_swig_HarryJNI_new_1DefStruct(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  DefStruct *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (DefStruct *)new DefStruct();
  *(DefStruct **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_eric_swig_HarryJNI_delete_1DefStruct(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  DefStruct *arg1 = (DefStruct *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(DefStruct **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_com_eric_swig_HarryJNI_new_1DefClass(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  DefClass *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (DefClass *)new DefClass();
  *(DefClass **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_eric_swig_HarryJNI_DefClass_1value_1int_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  DefClass *arg1 = (DefClass *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DefClass **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->value_int = arg2;
}


SWIGEXPORT jint JNICALL Java_com_eric_swig_HarryJNI_DefClass_1value_1int_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  DefClass *arg1 = (DefClass *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(DefClass **)&jarg1; 
  result = (int) ((arg1)->value_int);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_eric_swig_HarryJNI_delete_1DefClass(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  DefClass *arg1 = (DefClass *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(DefClass **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_com_eric_swig_HarryJNI_swig_1module_1init(JNIEnv *jenv, jclass jcls) {
  int i;
  
  static struct {
    const char *method;
    const char *signature;
  } methods[3] = {
    {
      "SwigDirector_CallbackStub_on_void_method", "(Lcom/eric/swig/CallbackStub;)V" 
    },
    {
      "SwigDirector_CallbackStub_on_string_method", "(Lcom/eric/swig/CallbackStub;Ljava/lang/String;)Ljava/lang/String;" 
    },
    {
      "SwigDirector_CallbackStub_on_byte_array_method", "(Lcom/eric/swig/CallbackStub;J)J" 
    }
  };
  Swig::jclass_HarryJNI = (jclass) jenv->NewGlobalRef(jcls);
  if (!Swig::jclass_HarryJNI) return;
  for (i = 0; i < (int) (sizeof(methods)/sizeof(methods[0])); ++i) {
    Swig::director_methids[i] = jenv->GetStaticMethodID(jcls, methods[i].method, methods[i].signature);
    if (!Swig::director_methids[i]) return;
  }
}


#ifdef __cplusplus
}
#endif

