/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.eric.swig;

public class DefStruct {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DefStruct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DefStruct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        HarryJNI.delete_DefStruct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setValue_int(int value) {
    HarryJNI.DefStruct_value_int_set(swigCPtr, this, value);
  }

  public int getValue_int() {
    return HarryJNI.DefStruct_value_int_get(swigCPtr, this);
  }

  public void setNet(NetType value) {
    HarryJNI.DefStruct_net_set(swigCPtr, this, value.swigValue());
  }

  public NetType getNet() {
    return NetType.swigToEnum(HarryJNI.DefStruct_net_get(swigCPtr, this));
  }

  public DefStruct() {
    this(HarryJNI.new_DefStruct(), true);
  }

}
