/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.eric.swig;

public class Harry {
  public static void init(CallbackStub callback) {
    HarryJNI.init(CallbackStub.getCPtr(callback), callback);
  }

  public static void void_method() {
    HarryJNI.void_method();
  }

  public static String string_method(String msg) {
    return HarryJNI.string_method(msg);
  }

  public static SWIGTYPE_p_signed_char byte_array_method(SWIGTYPE_p_signed_char arr) {
    long cPtr = HarryJNI.byte_array_method(SWIGTYPE_p_signed_char.getCPtr(arr));
    return (cPtr == 0) ? null : new SWIGTYPE_p_signed_char(cPtr, false);
  }

  public static SWIGTYPE_p_void void_ptr_method(Object object) {
    long cPtr = HarryJNI.void_ptr_method(object);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static void byte_array_input_method(byte[] buf) {
    HarryJNI.byte_array_input_method(buf);
  }

  public static void input_output_para(int[] para_inout, int[] para_out) {
    HarryJNI.input_output_para(para_inout, para_out);
  }

}
