/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.eric.swig;

public final class NetType {
  public final static NetType NET_UDP = new NetType("NET_UDP", HarryJNI.NET_UDP_get());
  public final static NetType NET_TCP = new NetType("NET_TCP", HarryJNI.NET_TCP_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static NetType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + NetType.class + " with value " + swigValue);
  }

  private NetType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private NetType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private NetType(String swigName, NetType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static NetType[] swigValues = { NET_UDP, NET_TCP };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

